language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=youversion --cov-report xml tests/
  - python-codacy-coverage -r coverage.xml

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  distributions: "sdist"
  on:
    branch: master
    tags: true
